<?php

//Web Server : Apache & Nignix

//Web Server is a software that serves web pages to users when they request them. It listens for incoming requests on a specific port (usually port 80 for HTTP and port 443 for HTTPS) and responds with the requested content, such as HTML pages, images, or other resources. Web servers can also handle dynamic content generated by server-side scripts, such as PHP, Python, or Ruby.
//XAMPP is a free and open-source cross-platform web server solution stack package developed by Apache Friends, consisting mainly of the Apache HTTP Server, MariaDB database, and interpreters for scripts written in the PHP and Perl programming languages. XAMPP is easy to install and use, making it a popular choice for developers who want to set up a local web server environment quickly.
//No multiple PHP Versions
//NO Multiple MySQL Versions
//Not for Production
//Difficult to maintain multiple projects
//

?>